### ISSUE TITLE
pip install aiida-yambo does not work

### ISSUE THREAD

**Issue by ltalirz** [yambo-code/yambo-aiida#80]
Hi guys, please fix the aiida-yambo package on pypi
```
 $ pip install aiida-yambo
Collecting aiida-yambo
  Downloading aiida-yambo-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/pip-build-2T4ZJz/aiida-yambo/setup.py", line 7, in <module>
        with open('setup.json', 'r') as info:
    IOError: [Errno 2] No such file or directory: 'setup.json'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/pip-build-2T4ZJz/aiida-yambo/
```

**Comment by mikeatm** [comment]
hmm, will take a look into this.

**Comment by mikeatm** [comment]
Please try with the latest tag release:[0.2.2](https://github.com/yambo-code/yambo-aiida/releases/tag/0.2.2)
`pip install "aiida-yambo>=0.2.2"`

**Comment by mikeatm** [comment]
Will close this once you confirm the fix

**Comment by ltalirz** [comment]
jup, fixed. Cheers
